name: CI on Push Tag

on: [push]
  # push:
    # tags:
    #   - '*'

env:
  IMAGE: rancher/system-upgrade-controller

jobs:
  test:
    runs-on: ubuntu-latest
    container: rancher/dapper:v0.6.0
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - name: Add Git
        run: apk add -U git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          flavor: |
            latest=false

      - name: Fix the not-a-git-repository issue
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests
        id: run-tests
        run: |
          dapper ci
          dapper e2e-sonobuoy
          dapper e2e-verify

      - name: Create GitHub release
        run: gh release create "${{ github.event.client_payload.tag }}" --prerelease --title "${{ github.event.client_payload.tag }}" /dist/artifacts/*