name: CI on Push Tag

on: [push]
  # push:
    # tags:
    #   - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container: rancher/dapper:v0.6.0
    permissions:
      contents: read
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - name: Add Git
        run: apk add -U git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fix the not-a-git-repository issue
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test
        run: |
          dapper ci
          dapper e2e-sonobuoy
          dapper e2e-verify
