name: CI

on: 
  push:
    branches:
      - 'gha'

env:
  IMAGE: test/test
  TAG: ${{ github.ref_name }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Generate dummy artifacts
        run: |
          mkdir -p dist/artifacts
          echo "test" > dist/artifacts/dummy.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: dist/artifacts/*
          if-no-files-found: error
          overwrite: true

  build-push-images:
    runs-on: ubuntu-latest
    needs: 
      - build-test
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          flavor: latest=false

      - name: Fix the not-a-git-repository issue
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/artifacts
          merge-multiple: true

      - name: Debug
        run: ls -lah dist/artifacts

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.test
          push: false
          tags: "${{ steps.meta.outputs.tags }}"
          platforms: "${{ matrix.os }}/${{ matrix.arch }}"
          labels: "${{ steps.meta.outputs.labels }}"
